### ISSUE TITLE
Chapter 12 Exercises Please Sir 🙏

### ISSUE THREAD

**Issue by XiiaoSky** [BalaurZmeu/Web_Programming_with_HTML5_CSS_and_JavaScript#1]
Please add Chapter 12 Exercises Sir, I haven't managed to answer it and my presentation 3 days more again 😭🙏

**Comment by BalaurZmeu** [comment]
I'm currently working on the Project for Chapter 11 and didn't read the Chapter 12 yet. I can give you only one advice. Open the book and do the exercises by yourself. This will help you understand the topic better. Even if you'll copy each question and paste it into the ChatGPT, reading the answers will help you understand the chapter better. I don't think I will manage to read the chapter so fast. I encourage you not to give up and to perform the exercises by yourself.

**Comment by BalaurZmeu** [comment]
Exercises for Chapter 12 are done. Sorry, I'm a slow learner and the chapter was difficult. I'm currently working on the project for Chapter 12.
